name: Build, test, and publish
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        version: 10.x
    - run: yarn install --frozen-lockfile
    - run: yarn test
    - run: yarn run semantic-release
      env:
        GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
